import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.SetProperty
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

abstract class CheckDependencyAllowlistTask : DefaultTask() {

    @get:Internal
    abstract val allowlistFile: RegularFileProperty

    @get:Input
    abstract val declaredDependencies: SetProperty<String>

    @get:Input
    abstract val declaredPlugins: SetProperty<String>

    @TaskAction
    fun check() {
        val allowedDeps = mutableSetOf<String>()
        val allowedPlugins = mutableSetOf<String>()

        val file = allowlistFile.get().asFile
        if (file.exists()) {
            file.forEachLine { line ->
                val trimmed = line.trim()
                if (trimmed.isEmpty() || trimmed.startsWith("#")) return@forEachLine
                when {
                    trimmed.startsWith("dep:") -> allowedDeps.add(trimmed.removePrefix("dep:"))
                    trimmed.startsWith("plugin:") -> allowedPlugins.add(trimmed.removePrefix("plugin:"))
                }
            }
        }

        val violations = mutableListOf<String>()

        declaredDependencies.get().forEach { dep ->
            if (dep !in allowedDeps) {
                violations.add("  dependency '$dep' is NOT in allowlist")
            }
        }

        declaredPlugins.get().forEach { plugin ->
            if (plugin !in allowedPlugins) {
                violations.add("  plugin '$plugin' is NOT in allowlist")
            }
        }

        if (violations.isNotEmpty()) {
            throw GradleException(
                "Dependency/plugin allowlist violations found:\n" +
                    violations.joinToString("\n") +
                    "\n\nRun './gradlew generateDependencyAllowlist' to update the allowlist."
            )
        }

        logger.lifecycle(
            "Dependency allowlist check passed. ${allowedDeps.size} dependencies, " +
                "${allowedPlugins.size} plugins verified."
        )
    }
}

abstract class GenerateDependencyAllowlistTask : DefaultTask() {

    @get:OutputFile
    abstract val allowlistFile: RegularFileProperty

    @get:Input
    abstract val declaredDependencies: SetProperty<String>

    @get:Input
    abstract val declaredPlugins: SetProperty<String>

    @TaskAction
    fun generate() {
        val deps = declaredDependencies.get().sorted()
        val plugins = declaredPlugins.get().sorted()

        val content = buildString {
            appendLine("# Dependency and plugin allowlist")
            appendLine("# Format: dep:groupId:artifactId or plugin:plugin.id")
            appendLine("# Auto-generated by generateDependencyAllowlist task")
            appendLine()
            appendLine("# Dependencies")
            deps.forEach { appendLine("dep:$it") }
            appendLine()
            appendLine("# Plugins")
            plugins.forEach { appendLine("plugin:$it") }
        }

        allowlistFile.get().asFile.writeText(content)
        logger.lifecycle(
            "Allowlist generated at gradle/dependency-allowlist.txt\n" +
                "  Dependencies: ${deps.size}\n" +
                "  Plugins: ${plugins.size}"
        )
    }
}
